# ワークフロー名
name: housework_bot
on: push
  #schedule:
    # 定期実行する時間・・・①
    #- cron: '* * * * *'

jobs:
  build:
    # Ubuntuの最新版環境内で処理を実行することを指定
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          # pip更新
          python -m pip install --upgrade pip
          # 必要なパッケージインストール・・・② 
          pip install requests
          pip install slack_bolt
          pip install pybit
          pip install certifi
          python3 -m certifi
          export SSL_CERT_FILE=$(python3 -m certifi)
          docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:3.141.59-xenon
          pip install selenium
          pip install gspread

      - name: Run script
        run: |
          # 定期実行するファイルを指定。・・・③
          python bybit.py
        env:
          Line_Notify_API_Key: ${{secrets.Line_Notify_API_Key}}
          Slack_BOT_API_Key: ${{secrets.Slack_BOT_API_Key}}
          Slack_APP_API_Key: ${{secrets.Slack_APP_API_Key}}
          Slack_Webhook_URL: ${{secrets.Slack_Webhook_URL}}
          Gmail_Address: ${{secrets.Gmail_Address}}
          Gmail_Password: ${{secrets.Gmail_Password}}
          Testnet_ByBit_API_Key: ${{secrets.Testnet_ByBit_API_Key}}
          Testnet_ByBit_Secret_Key: ${{secrets.Testnet_ByBit_Secret_Key}}
